name: Test Python Script on macOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-on-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Remplacez par la version Python nécessaire

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Assurez-vous que ce fichier contient vos dépendances

    - name: Run Python script
      run: |
        python your_script.py # Remplacez `your_script.py` par le nom de votre fichier
